apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app-chart.fullname" . }}
  labels:
    {{- include "web-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: http
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "web-app-chart.selectorLabels" . | nindent 4 }}
